- type: gameMapPool
  id: SpaceLabsDefaultMapPool
  maps:
  - CorvaxBox
  - CorvaxIshimura
  - Aspid
  - Bagel
  - Cluster
  - Core
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
