- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  sort: 0
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Juridical
  description: department-Juridical-description
  color: "#944A00"
  roles:
  - IAA

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  sort: 2
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  sort: 1
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  sort: 0
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  sort: 0
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  sort: 0
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  sort: 0
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
